name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Swift Lint
      run: swiftlint --strict
    - name: Build for all SDKs
      run: |
        xcodebuild clean build -project $PROJECT -scheme $SCHEME -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO;
        xcodebuild clean build -project $PROJECT -scheme $SCHEME -sdk macosx CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO;
        xcodebuild clean build -project $PROJECT -scheme $SCHEME -sdk appletvos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO;
      env:
        PROJECT: MultipeerHelper.xcodeproj
        SCHEME: MultipeerHelper-Package
