name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v3
    - name: Swift Lint 🧹
      run: swiftlint --strict
    - name: Test Build 🔨
      run: |
        xcodebuild clean build -scheme $SCHEME -destination 'generic/platform=iOS'
        xcodebuild clean build -scheme $SCHEME -destination 'platform=macOS'
        # xcodebuild clean build -scheme $SCHEME -destination 'platform=tvOS Simulator,name=Any tvOS Device'
      env:
        SCHEME: MultipeerHelper
